### ISSUE TITLE
은행 창구 관리 앱 [STEP1] L, Harry

### ISSUE THREAD

**Issue by LeeSe0ngYe0n** [LeeSe0ngYe0n/ios-bank-manager#1]
## Feature Issue
은행창구 관리 앱 STEP1 Queue 타입 구현을 위한 Linked List 타입 구현

## Todo
- [x] Linked List 타입 구현
- [x] Queue 타입 구현
- [x] Generic 활용
- [x] Unit Test 구현
